#!/usr/bin/env python3

import subprocess
import json
import time
import sys
import pathlib


# Rewrites include paths in MSVC compile commands to be valid in the workspace
# root instead of Bazel's execRoot.
def _patch_msvc_include_path(workspace_name, argument):
    # Example arguments generated by aquery in robinlinden/hastur:
    # * "/Iexternal/libpng+",
    # * "/external:Iexternal/libpng+",
    if argument.startswith("/Iexternal/"):
        argument = argument.replace(
            "/Iexternal/", f"/Ibazel-{workspace_name}/external/", 1
        )
    elif argument.startswith("/external:Iexternal/"):
        argument = argument.replace(
            "/external:Iexternal/",
            f"/external:Ibazel-{workspace_name}/external/",
            1,
        )
    return argument


def _patch_linux_include_path(workspace_name, argument):
    if argument.startswith("external/"):
        argument = argument.replace("external/", f"bazel-{workspace_name}/external/", 1)
    return argument


def main():
    start_time = time.time()

    project_root = subprocess.check_output(
        ["bazel", "info", "workspace"], text=True
    ).strip()

    project_name = project_root.rsplit("/")[-1]

    command = [
        "bazel",
        "aquery",
        # --include_param_files is broken on CppCompile actions, so we have to
        # disable the feature instead.
        # See: https://github.com/bazelbuild/bazel/issues/23293
        # "--include_param_files",
        "--features=-compiler_param_file",
        # layering_check adds a lot of '-fmodule-map-file'-arguments that aren't
        # useful for compile_commands.json.
        "--features=-layering_check",
        # In my projects, tooling is included in the target configuration as
        # well, and including the same file twice doesn't make much sense.
        "--notool_deps",
        "--output=jsonproto",
        # Allow the user to pass additional arguments, e.g. if they want a
        # --config or whatever.
        *sys.argv[1:],
        'mnemonic("CppCompile", deps(...))',
    ]

    print(f"Running '{' '.join(command)}'", file=sys.stderr)

    result = subprocess.run(command, capture_output=True, text=True, check=True)

    aquery_output = json.loads(result.stdout)
    actions = aquery_output.get("actions", [])

    compile_commands = []

    print(f"Found {len(actions)} actions in aquery output", file=sys.stderr)
    for action in actions:
        arguments = action.get("arguments", [])
        if not arguments:
            print(f"No arguments found for action: {action}", file=sys.stderr)
            continue

        is_msvc = pathlib.Path(arguments[0]).name == "cl.exe"

        for i, arg in enumerate(arguments):
            if is_msvc:
                arguments[i] = _patch_msvc_include_path(project_name, arg)
            elif arg in ("-iquote", "-isystem") and i + 1 < len(arguments):
                arguments[i + 1] = _patch_linux_include_path(
                    project_name, arguments[i + 1]
                )

            if arg in ("-c", "/c") and i + 1 < len(arguments):
                source_file = arguments[i + 1]
                compile_commands.append(
                    {
                        "directory": project_root,
                        "arguments": arguments,
                        "file": source_file,
                    }
                )
                break
        else:
            print(
                f"No source file found for action with arguments: {arguments}",
                file=sys.stderr,
            )

    with open(f"{project_root}/compile_commands.json", "w") as f:
        json.dump(compile_commands, f, indent=2)

    end_time = time.time()
    print(
        f"Wrote {len(compile_commands)} compile commands to {project_root}/compile_commands.json after {end_time - start_time:.2f} seconds",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
