on:
  pull_request:
  workflow_dispatch:
name: ci

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

jobs:
  ruff:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - run: pipx install ruff==0.16.6
      - run: ruff format --diff
      - run: ruff check
